### ISSUE TITLE
QQ 群号码可以公开么？

### ISSUE THREAD

**Issue by wenbing** [webpack-china/webpack-issues#1]
或者使用其他的讨论方式，使用 QQ 群感觉不够方便，特别是 mac 上无法从那个按钮进入，不知道怎么加入啊

**Comment by hello-lizhihua** [comment]
QQ 群号是425986482。
@lcxfs1991 mac qq 确实没法调用首页上那个链接

**Comment by lcxfs1991** [comment]
@wenbing 好的，我将qq群号也写上去

**Comment by lcxfs1991** [comment]
@wenbing 已经放上官网了
